name: lab3
version: 1.0

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Werror
  - -O2

library:
  source-dirs: src
  exposed_modules:
   - Bag

tests:
  lab1-test-suite:
    main: spec.hs
    source-dirs: test
    dependencies:
      - base
      - hspec
      - lab3
      - QuickCheck